name: soundpool_web
description: A Flutter Sound Pool for playing short audio files. Sound tracks are cached in memory and played directly from cache.
version: 2.2.0
homepage: https://github.com/ukasz123/soundpool/tree/master/soundpool_web

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.0.0'
  
dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter
  
  soundpool_platform_interface: 2.1.0
  
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: SoundpoolPlugin
        fileName: soundpool_web.dart
